### ISSUE TITLE
org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction.

### ISSUE THREAD

**Issue by wyrzyk** [atlassian-labs/db-replica#41]
```
Caused by: org.postgresql.util.PSQLException: Cannot change transaction isolation level in the middle of a transaction.
	at org.postgresql.jdbc.PgConnection.setTransactionIsolation(PgConnection.java:948)
	at com.atlassian.db.replica.internal.ConnectionParameters.initialize(ConnectionParameters.java:23)
	at com.atlassian.db.replica.internal.state.ConnectionState.prepareReadConnection(ConnectionState.java:187)
	at com.atlassian.db.replica.internal.state.ConnectionState.getReadConnection(ConnectionState.java:104)
	at com.atlassian.db.replica.internal.ReplicaConnectionProvider.getReadConnection(ReplicaConnectionProvider.java:43)
	at com.atlassian.db.replica.internal.ReplicaStatement$1.create(ReplicaStatement.java:32)
	at com.atlassian.db.replica.internal.ReplicaStatement$1.create(ReplicaStatement.java:29)
	at com.atlassian.db.replica.internal.LazyReference.get(LazyReference.java:20)
	... 54 more

```

**Comment by wyrzyk** [comment]
Fixed in `0.1.27`
